services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - .:/var/www/html
    env_file:
      - .env
    depends_on:
      - nginx
    networks:
      - laravel_network

  db:
    image: postgis/postgis:14-3.2
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - laravel_network

  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "8080:8080"
    volumes:
      - .:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - laravel_network

volumes:
  pgdata:

networks:
  laravel_network:
